project:
  type: book

book:
  title: "Advanced Computational Algorithms"
  author: "Moody Amakobe"
  publisher: "Global Data Science Institute"
  license: "CC BY 4.0"
  date: today
  cover-image: images/cover.png
  chapters:
    - part: "Preface"
      chapters: 
        - index.qmd
    - part: "Core Concepts"
      chapters:
        - chapters/01-introduction.qmd
        - chapters/02-Divide-and-Conquer.qmd
        - chapters/03-Data-Structures-for-Efficiency.qmd
        - chapters/04-Greedy-Algorithms.qmd
        - chapters/05-Dynamic-Programming.qmd
        - chapters/06-Randomized-Algorithms.qmd
        - chapters/07-Computational-Complexity.qmd
        - chapters/08-Approximation-Algorithms.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
  pdf:
    documentclass: scrreprt
  epub: default
